---
title: "All Things `R` spatial: Räumliche Daten in `R`"
subtitle: "Teil 3: Erste Schritte"
author: "Nils Ratnaweera (ZHAW)"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: [default, default-fonts, mystyle.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
    includes:
      after_body: insert-logo.html
---

layout: true
class: inverse

```{r, echo = FALSE}
library(fontawesome)
xaringanExtra::use_panelset()
```

## Erste Schritte `r fa("shoe-prints")`

---

- Mit ein bisschen Erfahrung in R ist die Handhabung von Geodaten kinderleicht

--

- Schauen wir uns mal die Lernumgebung an, die wir entwickelt haben

--

- dazu besuchen wir [arc2r.github.io/book](https://arc2r.github.io/book/)

???

- Handling vom Buch: TOC ein aus, Suchfunktion, Schriftgrösse und Art
- Warum englisch? um die Internationale R und GIS Community involvieren zu können 

---
layout: false

<TABLE CELLPADDING="2" CELLSPACING="3", style = "border-collapse:collapse; font-size: 75%; position: absolute; bottom: 50px; left:10px">
  <colgroup>
         <col span = 1, style="width: 12%; border-right: solid 1.5px; border-left: solid 1.5px">
         <col span = 1, style="width: 22%; border-right: solid 0.5px #E1DEE0">
         <col span = 1, style="width: 22%; border-right: solid 1.5px">
         <col span = 1, style="width: 22%; border-right: solid 0.5px #E1DEE0">
         <col span = 1, style="width: 22%; border-right: solid 1.5px">
  </colgroup>
   <TR>
      <TH></TH>
      <TH COLSPAN = "2">on your local machine</TH>
      <TH COLSPAN = "2">in the cloud</TH>
   </TR>
   <TR style = "border-bottom: 1px solid black">
      <TD></TD>
      <TD>a RStudio</TD>
      <TD>b different IDE</TD>
      <TD>c <a href="https://rstudio-ide.zhaw.ch)">ZHAW's Cloud</a></TD>
      <TD>d <a href="https://rstudio.cloud)">Rstudio Cloud</a></TD>

    </TR>
   <TR>
      <TD>1. Download and install R</TD>
      <TD COLSPAN = "2" ALIGN = "CENTER"> <a href="https://cran.r-project.org/)">CRAN</a>  </TD>
      <TD COLSPAN = "2" ALIGN = "CENTER">this step is not necessary</TD>
      
   </TR>
   <TR>
      <TD>2. Download and install IDE</TD>
      <TD><a href="https://rstudio.com/products/rstudio/download/	)">RStudio</a></TD>
      <TD>from the IDEs website</TD>
      <TD COLSPAN = "2" ALIGN = "CENTER">this step is not necessary</TD>

   </TR>
   <TR>
     <TD>3. Install the accompanying R Package "arc2r"	</TD>
     <TD COLSPAN = "2" ALIGN = "CENTER"><code>install_github("arc2r/arc2r")<br> # more detail below</code></TD>
     <TD>this step is not necessary	</TD>
     <TD><code><code>install_github("arc2r/arc2r")<br> # more detail below</code></TD>
   </TR>
   <TR>
     <TD>4. Create a new Project using the Templates	</TD>
     <TD>see Details below</TD>
     <TD>this feature is not available</TD>
     <TD>see Details below</TD>
     <TD>this feature is not available</TD>

   </TR>
   
</TABLE>


---




